/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GroupByInc.RetailApi.Client.Client.OpenAPIDateConverter;

namespace GroupByInc.RetailApi.Client.Model
{
    /// <summary>
    /// Merchandiser
    /// </summary>
    [DataContract(Name = "Merchandiser")]
    public partial class Merchandiser : IEquatable<Merchandiser>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Merchandiser" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Merchandiser() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Merchandiser" /> class.
        /// </summary>
        /// <param name="merchandiserId">merchandiserId (required).</param>
        public Merchandiser(string merchandiserId = default(string))
        {
            // to ensure "merchandiserId" is required (not null)
            if (merchandiserId == null)
            {
                throw new ArgumentNullException("merchandiserId is a required property for Merchandiser and cannot be null");
            }
            this.MerchandiserId = merchandiserId;
        }

        /// <summary>
        /// Gets or Sets MerchandiserId
        /// </summary>
        [DataMember(Name = "merchandiserId", IsRequired = true, EmitDefaultValue = true)]
        public string MerchandiserId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Merchandiser {\n");
            sb.Append("  MerchandiserId: ").Append(MerchandiserId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Merchandiser);
        }

        /// <summary>
        /// Returns true if Merchandiser instances are equal
        /// </summary>
        /// <param name="input">Instance of Merchandiser to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Merchandiser input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.MerchandiserId == input.MerchandiserId ||
                    (this.MerchandiserId != null &&
                    this.MerchandiserId.Equals(input.MerchandiserId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MerchandiserId != null)
                {
                    hashCode = (hashCode * 59) + this.MerchandiserId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
