/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GroupByInc.RetailApi.Client.Client.OpenAPIDateConverter;

namespace GroupByInc.RetailApi.Client.Model
{
    /// <summary>
    /// PinnedRefinement
    /// </summary>
    [DataContract(Name = "PinnedRefinement")]
    public partial class PinnedRefinement : IEquatable<PinnedRefinement>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PinnedRefinement" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PinnedRefinement() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PinnedRefinement" /> class.
        /// </summary>
        /// <param name="navigation">navigation (required).</param>
        /// <param name="refinements">refinements (required).</param>
        public PinnedRefinement(string navigation = default(string), List<Refinement> refinements = default(List<Refinement>))
        {
            // to ensure "navigation" is required (not null)
            if (navigation == null)
            {
                throw new ArgumentNullException("navigation is a required property for PinnedRefinement and cannot be null");
            }
            this.Navigation = navigation;
            // to ensure "refinements" is required (not null)
            if (refinements == null)
            {
                throw new ArgumentNullException("refinements is a required property for PinnedRefinement and cannot be null");
            }
            this.Refinements = refinements;
        }

        /// <summary>
        /// Gets or Sets Navigation
        /// </summary>
        [DataMember(Name = "navigation", IsRequired = true, EmitDefaultValue = true)]
        public string Navigation { get; set; }

        /// <summary>
        /// Gets or Sets Refinements
        /// </summary>
        [DataMember(Name = "refinements", IsRequired = true, EmitDefaultValue = true)]
        public List<Refinement> Refinements { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PinnedRefinement {\n");
            sb.Append("  Navigation: ").Append(Navigation).Append("\n");
            sb.Append("  Refinements: ").Append(Refinements).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PinnedRefinement);
        }

        /// <summary>
        /// Returns true if PinnedRefinement instances are equal
        /// </summary>
        /// <param name="input">Instance of PinnedRefinement to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PinnedRefinement input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Navigation == input.Navigation ||
                    (this.Navigation != null &&
                    this.Navigation.Equals(input.Navigation))
                ) && 
                (
                    this.Refinements == input.Refinements ||
                    this.Refinements != null &&
                    input.Refinements != null &&
                    this.Refinements.SequenceEqual(input.Refinements)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Navigation != null)
                {
                    hashCode = (hashCode * 59) + this.Navigation.GetHashCode();
                }
                if (this.Refinements != null)
                {
                    hashCode = (hashCode * 59) + this.Refinements.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
