/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GroupByInc.RetailApi.Client.Client.OpenAPIDateConverter;

namespace GroupByInc.RetailApi.Client.Model
{
    /// <summary>
    /// Defines QueryPatternTrigger.Type
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum QueryPatternTriggerType
    {
        /// <summary>
        /// Enum CONTAINS for value: CONTAINS
        /// </summary>
        [EnumMember(Value = "CONTAINS")]
        CONTAINS = 1,

        /// <summary>
        /// Enum ENDSWITH for value: ENDS_WITH
        /// </summary>
        [EnumMember(Value = "ENDS_WITH")]
        ENDSWITH = 2,

        /// <summary>
        /// Enum REGEX for value: REGEX
        /// </summary>
        [EnumMember(Value = "REGEX")]
        REGEX = 3,

        /// <summary>
        /// Enum STARTSWITH for value: STARTS_WITH
        /// </summary>
        [EnumMember(Value = "STARTS_WITH")]
        STARTSWITH = 4,

        /// <summary>
        /// Enum MATCHES for value: MATCHES
        /// </summary>
        [EnumMember(Value = "MATCHES")]
        MATCHES = 5
    }

}
