/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GroupByInc.RetailApi.Client.Client.OpenAPIDateConverter;

namespace GroupByInc.RetailApi.Client.Model
{
    /// <summary>
    /// Object with one single suggestion and associated info (brands and categories).
    /// </summary>
    [DataContract(Name = "SearchTerms")]
    public partial class SearchTerms : IEquatable<SearchTerms>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchTerms" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SearchTerms() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchTerms" /> class.
        /// </summary>
        /// <param name="value">Suggestion itself..</param>
        /// <param name="additionalInfo">additionalInfo (required).</param>
        public SearchTerms(string value = default(string), AdditionalInfo additionalInfo = default(AdditionalInfo))
        {
            // to ensure "additionalInfo" is required (not null)
            if (additionalInfo == null)
            {
                throw new ArgumentNullException("additionalInfo is a required property for SearchTerms and cannot be null");
            }
            this.AdditionalInfo = additionalInfo;
            this.Value = value;
        }

        /// <summary>
        /// Suggestion itself.
        /// </summary>
        /// <value>Suggestion itself.</value>
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public string Value { get; set; }

        /// <summary>
        /// Gets or Sets AdditionalInfo
        /// </summary>
        [DataMember(Name = "additionalInfo", IsRequired = true, EmitDefaultValue = true)]
        public AdditionalInfo AdditionalInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchTerms {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  AdditionalInfo: ").Append(AdditionalInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SearchTerms);
        }

        /// <summary>
        /// Returns true if SearchTerms instances are equal
        /// </summary>
        /// <param name="input">Instance of SearchTerms to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SearchTerms input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                ) && 
                (
                    this.AdditionalInfo == input.AdditionalInfo ||
                    (this.AdditionalInfo != null &&
                    this.AdditionalInfo.Equals(input.AdditionalInfo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Value.GetHashCode();
                }
                if (this.AdditionalInfo != null)
                {
                    hashCode = (hashCode * 59) + this.AdditionalInfo.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
