/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GroupByInc.RetailApi.Client.Client.OpenAPIDateConverter;

namespace GroupByInc.RetailApi.Client.Model
{
    /// <summary>
    /// Defines ZoneType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ZoneType
    {
        /// <summary>
        /// Enum QUERY for value: QUERY
        /// </summary>
        [EnumMember(Value = "QUERY")]
        QUERY = 1,

        /// <summary>
        /// Enum CONTENT for value: CONTENT
        /// </summary>
        [EnumMember(Value = "CONTENT")]
        CONTENT = 2,

        /// <summary>
        /// Enum RICHCONTENT for value: RICH_CONTENT
        /// </summary>
        [EnumMember(Value = "RICH_CONTENT")]
        RICHCONTENT = 3,

        /// <summary>
        /// Enum EXPECTQUERY for value: EXPECT_QUERY
        /// </summary>
        [EnumMember(Value = "EXPECT_QUERY")]
        EXPECTQUERY = 4,

        /// <summary>
        /// Enum GENERATEDCONTENT for value: GENERATED_CONTENT
        /// </summary>
        [EnumMember(Value = "GENERATED_CONTENT")]
        GENERATEDCONTENT = 5
    }

}
