/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using GroupByInc.RetailApi.Client.Client;
using GroupByInc.RetailApi.Client.Model;

namespace GroupByInc.RetailApi.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRecommendationsAPIApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Provide Recommendations AI functionality.
        /// </summary>
        /// <remarks>
        /// Perform a recommendation request against the GroupBy Retail Recommendations API.
        /// </remarks>
        /// <exception cref="GroupByInc.RetailApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xGroupbyCustomerId">Custom HTTP header which may contain tenant name. Used to define a client by its name.</param>
        /// <param name="recommendationsRequest">Request that should be populated to configure a recommendations API call made by the client.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PredictResults</returns>
        [Obsolete]
        PredictResults Predict(string xGroupbyCustomerId, RecommendationsRequest recommendationsRequest, int operationIndex = 0);

        /// <summary>
        /// Provide Recommendations AI functionality.
        /// </summary>
        /// <remarks>
        /// Perform a recommendation request against the GroupBy Retail Recommendations API.
        /// </remarks>
        /// <exception cref="GroupByInc.RetailApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xGroupbyCustomerId">Custom HTTP header which may contain tenant name. Used to define a client by its name.</param>
        /// <param name="recommendationsRequest">Request that should be populated to configure a recommendations API call made by the client.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PredictResults</returns>
        [Obsolete]
        ApiResponse<PredictResults> PredictWithHttpInfo(string xGroupbyCustomerId, RecommendationsRequest recommendationsRequest, int operationIndex = 0);
        /// <summary>
        /// Provide Recommendations AI functionality.
        /// </summary>
        /// <remarks>
        /// Perform a recommendation request against the GroupBy Retail Recommendations API.
        /// </remarks>
        /// <exception cref="GroupByInc.RetailApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xGroupbyCustomerId">Custom HTTP header which may contain tenant name. Used to define a client by its name.</param>
        /// <param name="recommendationsRequest">Request that should be populated to configure a recommendations API call made by the client.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PredictResults</returns>
        PredictResults PredictV2(string xGroupbyCustomerId, RecommendationsRequest recommendationsRequest, int operationIndex = 0);

        /// <summary>
        /// Provide Recommendations AI functionality.
        /// </summary>
        /// <remarks>
        /// Perform a recommendation request against the GroupBy Retail Recommendations API.
        /// </remarks>
        /// <exception cref="GroupByInc.RetailApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xGroupbyCustomerId">Custom HTTP header which may contain tenant name. Used to define a client by its name.</param>
        /// <param name="recommendationsRequest">Request that should be populated to configure a recommendations API call made by the client.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PredictResults</returns>
        ApiResponse<PredictResults> PredictV2WithHttpInfo(string xGroupbyCustomerId, RecommendationsRequest recommendationsRequest, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRecommendationsAPIApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Provide Recommendations AI functionality.
        /// </summary>
        /// <remarks>
        /// Perform a recommendation request against the GroupBy Retail Recommendations API.
        /// </remarks>
        /// <exception cref="GroupByInc.RetailApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xGroupbyCustomerId">Custom HTTP header which may contain tenant name. Used to define a client by its name.</param>
        /// <param name="recommendationsRequest">Request that should be populated to configure a recommendations API call made by the client.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PredictResults</returns>
        [Obsolete]
        System.Threading.Tasks.Task<PredictResults> PredictAsync(string xGroupbyCustomerId, RecommendationsRequest recommendationsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Provide Recommendations AI functionality.
        /// </summary>
        /// <remarks>
        /// Perform a recommendation request against the GroupBy Retail Recommendations API.
        /// </remarks>
        /// <exception cref="GroupByInc.RetailApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xGroupbyCustomerId">Custom HTTP header which may contain tenant name. Used to define a client by its name.</param>
        /// <param name="recommendationsRequest">Request that should be populated to configure a recommendations API call made by the client.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PredictResults)</returns>
        [Obsolete]
        System.Threading.Tasks.Task<ApiResponse<PredictResults>> PredictWithHttpInfoAsync(string xGroupbyCustomerId, RecommendationsRequest recommendationsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Provide Recommendations AI functionality.
        /// </summary>
        /// <remarks>
        /// Perform a recommendation request against the GroupBy Retail Recommendations API.
        /// </remarks>
        /// <exception cref="GroupByInc.RetailApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xGroupbyCustomerId">Custom HTTP header which may contain tenant name. Used to define a client by its name.</param>
        /// <param name="recommendationsRequest">Request that should be populated to configure a recommendations API call made by the client.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PredictResults</returns>
        System.Threading.Tasks.Task<PredictResults> PredictV2Async(string xGroupbyCustomerId, RecommendationsRequest recommendationsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Provide Recommendations AI functionality.
        /// </summary>
        /// <remarks>
        /// Perform a recommendation request against the GroupBy Retail Recommendations API.
        /// </remarks>
        /// <exception cref="GroupByInc.RetailApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xGroupbyCustomerId">Custom HTTP header which may contain tenant name. Used to define a client by its name.</param>
        /// <param name="recommendationsRequest">Request that should be populated to configure a recommendations API call made by the client.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PredictResults)</returns>
        System.Threading.Tasks.Task<ApiResponse<PredictResults>> PredictV2WithHttpInfoAsync(string xGroupbyCustomerId, RecommendationsRequest recommendationsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRecommendationsAPIApi : IRecommendationsAPIApiSync, IRecommendationsAPIApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RecommendationsAPIApi : IRecommendationsAPIApi
    {
        private GroupByInc.RetailApi.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RecommendationsAPIApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RecommendationsAPIApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RecommendationsAPIApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RecommendationsAPIApi(string basePath)
        {
            this.Configuration = GroupByInc.RetailApi.Client.Client.Configuration.MergeConfigurations(
                GroupByInc.RetailApi.Client.Client.GlobalConfiguration.Instance,
                new GroupByInc.RetailApi.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new GroupByInc.RetailApi.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new GroupByInc.RetailApi.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = GroupByInc.RetailApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RecommendationsAPIApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RecommendationsAPIApi(GroupByInc.RetailApi.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = GroupByInc.RetailApi.Client.Client.Configuration.MergeConfigurations(
                GroupByInc.RetailApi.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new GroupByInc.RetailApi.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new GroupByInc.RetailApi.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = GroupByInc.RetailApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RecommendationsAPIApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public RecommendationsAPIApi(GroupByInc.RetailApi.Client.Client.ISynchronousClient client, GroupByInc.RetailApi.Client.Client.IAsynchronousClient asyncClient, GroupByInc.RetailApi.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = GroupByInc.RetailApi.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public GroupByInc.RetailApi.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public GroupByInc.RetailApi.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public GroupByInc.RetailApi.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public GroupByInc.RetailApi.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Provide Recommendations AI functionality. Perform a recommendation request against the GroupBy Retail Recommendations API.
        /// </summary>
        /// <exception cref="GroupByInc.RetailApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xGroupbyCustomerId">Custom HTTP header which may contain tenant name. Used to define a client by its name.</param>
        /// <param name="recommendationsRequest">Request that should be populated to configure a recommendations API call made by the client.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PredictResults</returns>
        [Obsolete]
        public PredictResults Predict(string xGroupbyCustomerId, RecommendationsRequest recommendationsRequest, int operationIndex = 0)
        {
            GroupByInc.RetailApi.Client.Client.ApiResponse<PredictResults> localVarResponse = PredictWithHttpInfo(xGroupbyCustomerId, recommendationsRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Provide Recommendations AI functionality. Perform a recommendation request against the GroupBy Retail Recommendations API.
        /// </summary>
        /// <exception cref="GroupByInc.RetailApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xGroupbyCustomerId">Custom HTTP header which may contain tenant name. Used to define a client by its name.</param>
        /// <param name="recommendationsRequest">Request that should be populated to configure a recommendations API call made by the client.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PredictResults</returns>
        [Obsolete]
        public GroupByInc.RetailApi.Client.Client.ApiResponse<PredictResults> PredictWithHttpInfo(string xGroupbyCustomerId, RecommendationsRequest recommendationsRequest, int operationIndex = 0)
        {
            // verify the required parameter 'xGroupbyCustomerId' is set
            if (xGroupbyCustomerId == null)
            {
                throw new GroupByInc.RetailApi.Client.Client.ApiException(400, "Missing required parameter 'xGroupbyCustomerId' when calling RecommendationsAPIApi->Predict");
            }

            // verify the required parameter 'recommendationsRequest' is set
            if (recommendationsRequest == null)
            {
                throw new GroupByInc.RetailApi.Client.Client.ApiException(400, "Missing required parameter 'recommendationsRequest' when calling RecommendationsAPIApi->Predict");
            }

            GroupByInc.RetailApi.Client.Client.RequestOptions localVarRequestOptions = new GroupByInc.RetailApi.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GroupByInc.RetailApi.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GroupByInc.RetailApi.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("X-Groupby-Customer-Id", GroupByInc.RetailApi.Client.Client.ClientUtils.ParameterToString(xGroupbyCustomerId)); // header parameter
            localVarRequestOptions.Data = recommendationsRequest;

            localVarRequestOptions.Operation = "RecommendationsAPIApi.Predict";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (GroupByIncEmployee) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + GroupByInc.RetailApi.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (ClientKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<PredictResults>("/api/predict", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Predict", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Provide Recommendations AI functionality. Perform a recommendation request against the GroupBy Retail Recommendations API.
        /// </summary>
        /// <exception cref="GroupByInc.RetailApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xGroupbyCustomerId">Custom HTTP header which may contain tenant name. Used to define a client by its name.</param>
        /// <param name="recommendationsRequest">Request that should be populated to configure a recommendations API call made by the client.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PredictResults</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<PredictResults> PredictAsync(string xGroupbyCustomerId, RecommendationsRequest recommendationsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            GroupByInc.RetailApi.Client.Client.ApiResponse<PredictResults> localVarResponse = await PredictWithHttpInfoAsync(xGroupbyCustomerId, recommendationsRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Provide Recommendations AI functionality. Perform a recommendation request against the GroupBy Retail Recommendations API.
        /// </summary>
        /// <exception cref="GroupByInc.RetailApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xGroupbyCustomerId">Custom HTTP header which may contain tenant name. Used to define a client by its name.</param>
        /// <param name="recommendationsRequest">Request that should be populated to configure a recommendations API call made by the client.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PredictResults)</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<GroupByInc.RetailApi.Client.Client.ApiResponse<PredictResults>> PredictWithHttpInfoAsync(string xGroupbyCustomerId, RecommendationsRequest recommendationsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'xGroupbyCustomerId' is set
            if (xGroupbyCustomerId == null)
            {
                throw new GroupByInc.RetailApi.Client.Client.ApiException(400, "Missing required parameter 'xGroupbyCustomerId' when calling RecommendationsAPIApi->Predict");
            }

            // verify the required parameter 'recommendationsRequest' is set
            if (recommendationsRequest == null)
            {
                throw new GroupByInc.RetailApi.Client.Client.ApiException(400, "Missing required parameter 'recommendationsRequest' when calling RecommendationsAPIApi->Predict");
            }


            GroupByInc.RetailApi.Client.Client.RequestOptions localVarRequestOptions = new GroupByInc.RetailApi.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GroupByInc.RetailApi.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GroupByInc.RetailApi.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("X-Groupby-Customer-Id", GroupByInc.RetailApi.Client.Client.ClientUtils.ParameterToString(xGroupbyCustomerId)); // header parameter
            localVarRequestOptions.Data = recommendationsRequest;

            localVarRequestOptions.Operation = "RecommendationsAPIApi.Predict";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (GroupByIncEmployee) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + GroupByInc.RetailApi.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (ClientKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<PredictResults>("/api/predict", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Predict", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Provide Recommendations AI functionality. Perform a recommendation request against the GroupBy Retail Recommendations API.
        /// </summary>
        /// <exception cref="GroupByInc.RetailApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xGroupbyCustomerId">Custom HTTP header which may contain tenant name. Used to define a client by its name.</param>
        /// <param name="recommendationsRequest">Request that should be populated to configure a recommendations API call made by the client.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PredictResults</returns>
        public PredictResults PredictV2(string xGroupbyCustomerId, RecommendationsRequest recommendationsRequest, int operationIndex = 0)
        {
            GroupByInc.RetailApi.Client.Client.ApiResponse<PredictResults> localVarResponse = PredictV2WithHttpInfo(xGroupbyCustomerId, recommendationsRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Provide Recommendations AI functionality. Perform a recommendation request against the GroupBy Retail Recommendations API.
        /// </summary>
        /// <exception cref="GroupByInc.RetailApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xGroupbyCustomerId">Custom HTTP header which may contain tenant name. Used to define a client by its name.</param>
        /// <param name="recommendationsRequest">Request that should be populated to configure a recommendations API call made by the client.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PredictResults</returns>
        public GroupByInc.RetailApi.Client.Client.ApiResponse<PredictResults> PredictV2WithHttpInfo(string xGroupbyCustomerId, RecommendationsRequest recommendationsRequest, int operationIndex = 0)
        {
            // verify the required parameter 'xGroupbyCustomerId' is set
            if (xGroupbyCustomerId == null)
            {
                throw new GroupByInc.RetailApi.Client.Client.ApiException(400, "Missing required parameter 'xGroupbyCustomerId' when calling RecommendationsAPIApi->PredictV2");
            }

            // verify the required parameter 'recommendationsRequest' is set
            if (recommendationsRequest == null)
            {
                throw new GroupByInc.RetailApi.Client.Client.ApiException(400, "Missing required parameter 'recommendationsRequest' when calling RecommendationsAPIApi->PredictV2");
            }

            GroupByInc.RetailApi.Client.Client.RequestOptions localVarRequestOptions = new GroupByInc.RetailApi.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GroupByInc.RetailApi.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GroupByInc.RetailApi.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("X-Groupby-Customer-Id", GroupByInc.RetailApi.Client.Client.ClientUtils.ParameterToString(xGroupbyCustomerId)); // header parameter
            localVarRequestOptions.Data = recommendationsRequest;

            localVarRequestOptions.Operation = "RecommendationsAPIApi.PredictV2";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (GroupByIncEmployee) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + GroupByInc.RetailApi.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (ClientKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<PredictResults>("/api/recommendation", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PredictV2", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Provide Recommendations AI functionality. Perform a recommendation request against the GroupBy Retail Recommendations API.
        /// </summary>
        /// <exception cref="GroupByInc.RetailApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xGroupbyCustomerId">Custom HTTP header which may contain tenant name. Used to define a client by its name.</param>
        /// <param name="recommendationsRequest">Request that should be populated to configure a recommendations API call made by the client.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PredictResults</returns>
        public async System.Threading.Tasks.Task<PredictResults> PredictV2Async(string xGroupbyCustomerId, RecommendationsRequest recommendationsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            GroupByInc.RetailApi.Client.Client.ApiResponse<PredictResults> localVarResponse = await PredictV2WithHttpInfoAsync(xGroupbyCustomerId, recommendationsRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Provide Recommendations AI functionality. Perform a recommendation request against the GroupBy Retail Recommendations API.
        /// </summary>
        /// <exception cref="GroupByInc.RetailApi.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xGroupbyCustomerId">Custom HTTP header which may contain tenant name. Used to define a client by its name.</param>
        /// <param name="recommendationsRequest">Request that should be populated to configure a recommendations API call made by the client.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PredictResults)</returns>
        public async System.Threading.Tasks.Task<GroupByInc.RetailApi.Client.Client.ApiResponse<PredictResults>> PredictV2WithHttpInfoAsync(string xGroupbyCustomerId, RecommendationsRequest recommendationsRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'xGroupbyCustomerId' is set
            if (xGroupbyCustomerId == null)
            {
                throw new GroupByInc.RetailApi.Client.Client.ApiException(400, "Missing required parameter 'xGroupbyCustomerId' when calling RecommendationsAPIApi->PredictV2");
            }

            // verify the required parameter 'recommendationsRequest' is set
            if (recommendationsRequest == null)
            {
                throw new GroupByInc.RetailApi.Client.Client.ApiException(400, "Missing required parameter 'recommendationsRequest' when calling RecommendationsAPIApi->PredictV2");
            }


            GroupByInc.RetailApi.Client.Client.RequestOptions localVarRequestOptions = new GroupByInc.RetailApi.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = GroupByInc.RetailApi.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = GroupByInc.RetailApi.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("X-Groupby-Customer-Id", GroupByInc.RetailApi.Client.Client.ClientUtils.ParameterToString(xGroupbyCustomerId)); // header parameter
            localVarRequestOptions.Data = recommendationsRequest;

            localVarRequestOptions.Operation = "RecommendationsAPIApi.PredictV2";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (GroupByIncEmployee) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + GroupByInc.RetailApi.Client.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (ClientKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<PredictResults>("/api/recommendation", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PredictV2", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
