/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using GroupByInc.RetailApi.Client.Client;
using GroupByInc.RetailApi.Client.Api;
// uncomment below to import models
//using GroupByInc.RetailApi.Client.Model;

namespace GroupByInc.RetailApi.Client.Test.Api
{
    /// <summary>
    ///  Class for testing AutocompleteApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AutocompleteApiTests : IDisposable
    {
        private AutocompleteApi instance;

        public AutocompleteApiTests()
        {
            instance = new AutocompleteApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AutocompleteApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AutocompleteApi
            //Assert.IsType<AutocompleteApi>(instance);
        }

        /// <summary>
        /// Test Autocompletesearch
        /// </summary>
        [Fact]
        public void AutocompletesearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xGroupbyCustomerId = null;
            //Identity identity = null;
            //Merchandiser merchandiser = null;
            //Request? request = null;
            //var response = instance.Autocompletesearch(xGroupbyCustomerId, identity, merchandiser, request);
            //Assert.IsType<SearchResults>(response);
        }
    }
}
