/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using GroupByInc.RetailApi.Client.Client;
using GroupByInc.RetailApi.Client.Api;
// uncomment below to import models
//using GroupByInc.RetailApi.Client.Model;

namespace GroupByInc.RetailApi.Client.Test.Api
{
    /// <summary>
    ///  Class for testing RecommendationsAPIApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RecommendationsAPIApiTests : IDisposable
    {
        private RecommendationsAPIApi instance;

        public RecommendationsAPIApiTests()
        {
            instance = new RecommendationsAPIApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RecommendationsAPIApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' RecommendationsAPIApi
            //Assert.IsType<RecommendationsAPIApi>(instance);
        }

        /// <summary>
        /// Test Predict
        /// </summary>
        [Fact]
        public void PredictTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xGroupbyCustomerId = null;
            //RecommendationsRequest recommendationsRequest = null;
            //var response = instance.Predict(xGroupbyCustomerId, recommendationsRequest);
            //Assert.IsType<PredictResults>(response);
        }

        /// <summary>
        /// Test PredictV2
        /// </summary>
        [Fact]
        public void PredictV2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xGroupbyCustomerId = null;
            //RecommendationsRequest recommendationsRequest = null;
            //var response = instance.PredictV2(xGroupbyCustomerId, recommendationsRequest);
            //Assert.IsType<PredictResults>(response);
        }
    }
}
