/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AdditionalInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdditionalInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdditionalInfo
        //private AdditionalInfo instance;

        public AdditionalInfoTests()
        {
            // TODO uncomment below to create an instance of AdditionalInfo
            //instance = new AdditionalInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdditionalInfo
        /// </summary>
        [Fact]
        public void AdditionalInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdditionalInfo
            //Assert.IsType<AdditionalInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Brands'
        /// </summary>
        [Fact]
        public void BrandsTest()
        {
            // TODO unit test for the property 'Brands'
        }

        /// <summary>
        /// Test the property 'Categories'
        /// </summary>
        [Fact]
        public void CategoriesTest()
        {
            // TODO unit test for the property 'Categories'
        }
    }
}
