/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing BiasDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BiasDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BiasDto
        //private BiasDto instance;

        public BiasDtoTests()
        {
            // TODO uncomment below to create an instance of BiasDto
            //instance = new BiasDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BiasDto
        /// </summary>
        [Fact]
        public void BiasDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" BiasDto
            //Assert.IsType<BiasDto>(instance);
        }

        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

        /// <summary>
        /// Test the property 'Strength'
        /// </summary>
        [Fact]
        public void StrengthTest()
        {
            // TODO unit test for the property 'Strength'
        }
    }
}
