/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing BiasingProfileDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BiasingProfileDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BiasingProfileDto
        //private BiasingProfileDto instance;

        public BiasingProfileDtoTests()
        {
            // TODO uncomment below to create an instance of BiasingProfileDto
            //instance = new BiasingProfileDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BiasingProfileDto
        /// </summary>
        [Fact]
        public void BiasingProfileDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" BiasingProfileDto
            //Assert.IsType<BiasingProfileDto>(instance);
        }

        /// <summary>
        /// Test the property 'Biases'
        /// </summary>
        [Fact]
        public void BiasesTest()
        {
            // TODO unit test for the property 'Biases'
        }
    }
}
