/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing BoostedProductBucket
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BoostedProductBucketTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BoostedProductBucket
        //private BoostedProductBucket instance;

        public BoostedProductBucketTests()
        {
            // TODO uncomment below to create an instance of BoostedProductBucket
            //instance = new BoostedProductBucket();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BoostedProductBucket
        /// </summary>
        [Fact]
        public void BoostedProductBucketInstanceTest()
        {
            // TODO uncomment below to test "IsType" BoostedProductBucket
            //Assert.IsType<BoostedProductBucket>(instance);
        }

        /// <summary>
        /// Test the property 'Products'
        /// </summary>
        [Fact]
        public void ProductsTest()
        {
            // TODO unit test for the property 'Products'
        }
    }
}
