/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ColorInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ColorInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ColorInfo
        //private ColorInfo instance;

        public ColorInfoTests()
        {
            // TODO uncomment below to create an instance of ColorInfo
            //instance = new ColorInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ColorInfo
        /// </summary>
        [Fact]
        public void ColorInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ColorInfo
            //Assert.IsType<ColorInfo>(instance);
        }

        /// <summary>
        /// Test the property 'ColorFamilies'
        /// </summary>
        [Fact]
        public void ColorFamiliesTest()
        {
            // TODO unit test for the property 'ColorFamilies'
        }

        /// <summary>
        /// Test the property 'Colors'
        /// </summary>
        [Fact]
        public void ColorsTest()
        {
            // TODO unit test for the property 'Colors'
        }
    }
}
