/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CustomParameterTrigger
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomParameterTriggerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomParameterTrigger
        //private CustomParameterTrigger instance;

        public CustomParameterTriggerTests()
        {
            // TODO uncomment below to create an instance of CustomParameterTrigger
            //instance = new CustomParameterTrigger();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomParameterTrigger
        /// </summary>
        [Fact]
        public void CustomParameterTriggerInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomParameterTrigger
            //Assert.IsType<CustomParameterTrigger>(instance);
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
