/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DebugDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DebugDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DebugDto
        //private DebugDto instance;

        public DebugDtoTests()
        {
            // TODO uncomment below to create an instance of DebugDto
            //instance = new DebugDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DebugDto
        /// </summary>
        [Fact]
        public void DebugDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" DebugDto
            //Assert.IsType<DebugDto>(instance);
        }

        /// <summary>
        /// Test the property 'RawSearchRequest'
        /// </summary>
        [Fact]
        public void RawSearchRequestTest()
        {
            // TODO unit test for the property 'RawSearchRequest'
        }

        /// <summary>
        /// Test the property 'RawSearchResponse'
        /// </summary>
        [Fact]
        public void RawSearchResponseTest()
        {
            // TODO unit test for the property 'RawSearchResponse'
        }
    }
}
