/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ExperimentVariant
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExperimentVariantTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExperimentVariant
        //private ExperimentVariant instance;

        public ExperimentVariantTests()
        {
            // TODO uncomment below to create an instance of ExperimentVariant
            //instance = new ExperimentVariant();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExperimentVariant
        /// </summary>
        [Fact]
        public void ExperimentVariantInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExperimentVariant
            //Assert.IsType<ExperimentVariant>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'RuleVariant'
        /// </summary>
        [Fact]
        public void RuleVariantTest()
        {
            // TODO unit test for the property 'RuleVariant'
        }

        /// <summary>
        /// Test the property 'VariantTriggerPercentage'
        /// </summary>
        [Fact]
        public void VariantTriggerPercentageTest()
        {
            // TODO unit test for the property 'VariantTriggerPercentage'
        }
    }
}
