/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing FacetSearchRequestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FacetSearchRequestDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FacetSearchRequestDto
        //private FacetSearchRequestDto instance;

        public FacetSearchRequestDtoTests()
        {
            // TODO uncomment below to create an instance of FacetSearchRequestDto
            //instance = new FacetSearchRequestDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FacetSearchRequestDto
        /// </summary>
        [Fact]
        public void FacetSearchRequestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" FacetSearchRequestDto
            //Assert.IsType<FacetSearchRequestDto>(instance);
        }

        /// <summary>
        /// Test the property 'Facet'
        /// </summary>
        [Fact]
        public void FacetTest()
        {
            // TODO unit test for the property 'Facet'
        }

        /// <summary>
        /// Test the property 'OriginalRequest'
        /// </summary>
        [Fact]
        public void OriginalRequestTest()
        {
            // TODO unit test for the property 'OriginalRequest'
        }
    }
}
