/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing FacetSearchResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FacetSearchResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FacetSearchResponseDto
        //private FacetSearchResponseDto instance;

        public FacetSearchResponseDtoTests()
        {
            // TODO uncomment below to create an instance of FacetSearchResponseDto
            //instance = new FacetSearchResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FacetSearchResponseDto
        /// </summary>
        [Fact]
        public void FacetSearchResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" FacetSearchResponseDto
            //Assert.IsType<FacetSearchResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'OriginalRequest'
        /// </summary>
        [Fact]
        public void OriginalRequestTest()
        {
            // TODO unit test for the property 'OriginalRequest'
        }

        /// <summary>
        /// Test the property 'AvailableNavigation'
        /// </summary>
        [Fact]
        public void AvailableNavigationTest()
        {
            // TODO unit test for the property 'AvailableNavigation'
        }
    }
}
