/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing FulfillmentInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FulfillmentInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FulfillmentInfo
        //private FulfillmentInfo instance;

        public FulfillmentInfoTests()
        {
            // TODO uncomment below to create an instance of FulfillmentInfo
            //instance = new FulfillmentInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FulfillmentInfo
        /// </summary>
        [Fact]
        public void FulfillmentInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" FulfillmentInfo
            //Assert.IsType<FulfillmentInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'PlaceIds'
        /// </summary>
        [Fact]
        public void PlaceIdsTest()
        {
            // TODO unit test for the property 'PlaceIds'
        }
    }
}
