/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Merchandiser
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MerchandiserTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Merchandiser
        //private Merchandiser instance;

        public MerchandiserTests()
        {
            // TODO uncomment below to create an instance of Merchandiser
            //instance = new Merchandiser();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Merchandiser
        /// </summary>
        [Fact]
        public void MerchandiserInstanceTest()
        {
            // TODO uncomment below to test "IsType" Merchandiser
            //Assert.IsType<Merchandiser>(instance);
        }

        /// <summary>
        /// Test the property 'MerchandiserId'
        /// </summary>
        [Fact]
        public void MerchandiserIdTest()
        {
            // TODO unit test for the property 'MerchandiserId'
        }
    }
}
