/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing NavigationTypeDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NavigationTypeDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NavigationTypeDto
        //private NavigationTypeDto instance;

        public NavigationTypeDtoTests()
        {
            // TODO uncomment below to create an instance of NavigationTypeDto
            //instance = new NavigationTypeDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NavigationTypeDto
        /// </summary>
        [Fact]
        public void NavigationTypeDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" NavigationTypeDto
            //Assert.IsType<NavigationTypeDto>(instance);
        }
    }
}
