/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Overwrites
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OverwritesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Overwrites
        //private Overwrites instance;

        public OverwritesTests()
        {
            // TODO uncomment below to create an instance of Overwrites
            //instance = new Overwrites();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Overwrites
        /// </summary>
        [Fact]
        public void OverwritesInstanceTest()
        {
            // TODO uncomment below to test "IsType" Overwrites
            //Assert.IsType<Overwrites>(instance);
        }

        /// <summary>
        /// Test the property 'Rules'
        /// </summary>
        [Fact]
        public void RulesTest()
        {
            // TODO unit test for the property 'Rules'
        }
    }
}
