/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PageInfoDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PageInfoDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PageInfoDto
        //private PageInfoDto instance;

        public PageInfoDtoTests()
        {
            // TODO uncomment below to create an instance of PageInfoDto
            //instance = new PageInfoDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PageInfoDto
        /// </summary>
        [Fact]
        public void PageInfoDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PageInfoDto
            //Assert.IsType<PageInfoDto>(instance);
        }

        /// <summary>
        /// Test the property 'RecordStart'
        /// </summary>
        [Fact]
        public void RecordStartTest()
        {
            // TODO unit test for the property 'RecordStart'
        }

        /// <summary>
        /// Test the property 'RecordEnd'
        /// </summary>
        [Fact]
        public void RecordEndTest()
        {
            // TODO unit test for the property 'RecordEnd'
        }
    }
}
