/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PredictResults
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PredictResultsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PredictResults
        //private PredictResults instance;

        public PredictResultsTests()
        {
            // TODO uncomment below to create an instance of PredictResults
            //instance = new PredictResults();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PredictResults
        /// </summary>
        [Fact]
        public void PredictResultsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PredictResults
            //Assert.IsType<PredictResults>(instance);
        }

        /// <summary>
        /// Test the property 'Warnings'
        /// </summary>
        [Fact]
        public void WarningsTest()
        {
            // TODO unit test for the property 'Warnings'
        }

        /// <summary>
        /// Test the property 'Products'
        /// </summary>
        [Fact]
        public void ProductsTest()
        {
            // TODO unit test for the property 'Products'
        }

        /// <summary>
        /// Test the property 'Records'
        /// </summary>
        [Fact]
        public void RecordsTest()
        {
            // TODO unit test for the property 'Records'
        }

        /// <summary>
        /// Test the property 'ModelId'
        /// </summary>
        [Fact]
        public void ModelIdTest()
        {
            // TODO unit test for the property 'ModelId'
        }

        /// <summary>
        /// Test the property 'ModelName'
        /// </summary>
        [Fact]
        public void ModelNameTest()
        {
            // TODO unit test for the property 'ModelName'
        }

        /// <summary>
        /// Test the property 'ModelType'
        /// </summary>
        [Fact]
        public void ModelTypeTest()
        {
            // TODO unit test for the property 'ModelType'
        }

        /// <summary>
        /// Test the property 'OptimizationObjective'
        /// </summary>
        [Fact]
        public void OptimizationObjectiveTest()
        {
            // TODO unit test for the property 'OptimizationObjective'
        }

        /// <summary>
        /// Test the property 'FilterSet'
        /// </summary>
        [Fact]
        public void FilterSetTest()
        {
            // TODO unit test for the property 'FilterSet'
        }

        /// <summary>
        /// Test the property 'RawFilter'
        /// </summary>
        [Fact]
        public void RawFilterTest()
        {
            // TODO unit test for the property 'RawFilter'
        }

        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
    }
}
