/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PriceInfoPriceRange
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PriceInfoPriceRangeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PriceInfoPriceRange
        //private PriceInfoPriceRange instance;

        public PriceInfoPriceRangeTests()
        {
            // TODO uncomment below to create an instance of PriceInfoPriceRange
            //instance = new PriceInfoPriceRange();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PriceInfoPriceRange
        /// </summary>
        [Fact]
        public void PriceInfoPriceRangeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PriceInfoPriceRange
            //Assert.IsType<PriceInfoPriceRange>(instance);
        }

        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

        /// <summary>
        /// Test the property 'OriginalPrice'
        /// </summary>
        [Fact]
        public void OriginalPriceTest()
        {
            // TODO unit test for the property 'OriginalPrice'
        }
    }
}
