/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PriceInfoPriceEffectiveTime
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PriceInfoPriceEffectiveTimeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PriceInfoPriceEffectiveTime
        //private PriceInfoPriceEffectiveTime instance;

        public PriceInfoPriceEffectiveTimeTests()
        {
            // TODO uncomment below to create an instance of PriceInfoPriceEffectiveTime
            //instance = new PriceInfoPriceEffectiveTime();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PriceInfoPriceEffectiveTime
        /// </summary>
        [Fact]
        public void PriceInfoPriceEffectiveTimeInstanceTest()
        {
            // TODO uncomment below to test "IsType" PriceInfoPriceEffectiveTime
            //Assert.IsType<PriceInfoPriceEffectiveTime>(instance);
        }

        /// <summary>
        /// Test the property 'Seconds'
        /// </summary>
        [Fact]
        public void SecondsTest()
        {
            // TODO unit test for the property 'Seconds'
        }

        /// <summary>
        /// Test the property 'Nanos'
        /// </summary>
        [Fact]
        public void NanosTest()
        {
            // TODO unit test for the property 'Nanos'
        }
    }
}
