/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ProductDtoColorInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductDtoColorInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductDtoColorInfo
        //private ProductDtoColorInfo instance;

        public ProductDtoColorInfoTests()
        {
            // TODO uncomment below to create an instance of ProductDtoColorInfo
            //instance = new ProductDtoColorInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductDtoColorInfo
        /// </summary>
        [Fact]
        public void ProductDtoColorInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductDtoColorInfo
            //Assert.IsType<ProductDtoColorInfo>(instance);
        }

        /// <summary>
        /// Test the property 'ColorFamilies'
        /// </summary>
        [Fact]
        public void ColorFamiliesTest()
        {
            // TODO unit test for the property 'ColorFamilies'
        }

        /// <summary>
        /// Test the property 'Colors'
        /// </summary>
        [Fact]
        public void ColorsTest()
        {
            // TODO unit test for the property 'Colors'
        }
    }
}
