/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ProductDtoAvailableTime
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductDtoAvailableTimeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductDtoAvailableTime
        //private ProductDtoAvailableTime instance;

        public ProductDtoAvailableTimeTests()
        {
            // TODO uncomment below to create an instance of ProductDtoAvailableTime
            //instance = new ProductDtoAvailableTime();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductDtoAvailableTime
        /// </summary>
        [Fact]
        public void ProductDtoAvailableTimeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductDtoAvailableTime
            //Assert.IsType<ProductDtoAvailableTime>(instance);
        }

        /// <summary>
        /// Test the property 'Seconds'
        /// </summary>
        [Fact]
        public void SecondsTest()
        {
            // TODO unit test for the property 'Seconds'
        }

        /// <summary>
        /// Test the property 'Nanos'
        /// </summary>
        [Fact]
        public void NanosTest()
        {
            // TODO unit test for the property 'Nanos'
        }
    }
}
