/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ProductCustomAttribute
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductCustomAttributeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductCustomAttribute
        //private ProductCustomAttribute instance;

        public ProductCustomAttributeTests()
        {
            // TODO uncomment below to create an instance of ProductCustomAttribute
            //instance = new ProductCustomAttribute();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductCustomAttribute
        /// </summary>
        [Fact]
        public void ProductCustomAttributeInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductCustomAttribute
            //Assert.IsType<ProductCustomAttribute>(instance);
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'Numbers'
        /// </summary>
        [Fact]
        public void NumbersTest()
        {
            // TODO unit test for the property 'Numbers'
        }

        /// <summary>
        /// Test the property 'Searchable'
        /// </summary>
        [Fact]
        public void SearchableTest()
        {
            // TODO unit test for the property 'Searchable'
        }

        /// <summary>
        /// Test the property 'Indexable'
        /// </summary>
        [Fact]
        public void IndexableTest()
        {
            // TODO unit test for the property 'Indexable'
        }
    }
}
