/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Range
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RangeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Range
        //private Range instance;

        public RangeTests()
        {
            // TODO uncomment below to create an instance of Range
            //instance = new Range();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Range
        /// </summary>
        [Fact]
        public void RangeInstanceTest()
        {
            // TODO uncomment below to test "IsType" Range
            //Assert.IsType<Range>(instance);
        }

        /// <summary>
        /// Test the property 'Low'
        /// </summary>
        [Fact]
        public void LowTest()
        {
            // TODO unit test for the property 'Low'
        }

        /// <summary>
        /// Test the property 'High'
        /// </summary>
        [Fact]
        public void HighTest()
        {
            // TODO unit test for the property 'High'
        }
    }
}
