/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Rating
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RatingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Rating
        //private Rating instance;

        public RatingTests()
        {
            // TODO uncomment below to create an instance of Rating
            //instance = new Rating();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Rating
        /// </summary>
        [Fact]
        public void RatingInstanceTest()
        {
            // TODO uncomment below to test "IsType" Rating
            //Assert.IsType<Rating>(instance);
        }

        /// <summary>
        /// Test the property 'RatingCount'
        /// </summary>
        [Fact]
        public void RatingCountTest()
        {
            // TODO unit test for the property 'RatingCount'
        }

        /// <summary>
        /// Test the property 'AverageRating'
        /// </summary>
        [Fact]
        public void AverageRatingTest()
        {
            // TODO unit test for the property 'AverageRating'
        }

        /// <summary>
        /// Test the property 'RatingHistogram'
        /// </summary>
        [Fact]
        public void RatingHistogramTest()
        {
            // TODO unit test for the property 'RatingHistogram'
        }
    }
}
