/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing RuleTemplate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RuleTemplateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RuleTemplate
        //private RuleTemplate instance;

        public RuleTemplateTests()
        {
            // TODO uncomment below to create an instance of RuleTemplate
            //instance = new RuleTemplate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RuleTemplate
        /// </summary>
        [Fact]
        public void RuleTemplateInstanceTest()
        {
            // TODO uncomment below to test "IsType" RuleTemplate
            //Assert.IsType<RuleTemplate>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'EnableExactMatching'
        /// </summary>
        [Fact]
        public void EnableExactMatchingTest()
        {
            // TODO unit test for the property 'EnableExactMatching'
        }

        /// <summary>
        /// Test the property 'Sections'
        /// </summary>
        [Fact]
        public void SectionsTest()
        {
            // TODO unit test for the property 'Sections'
        }
    }
}
