/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing RuleTemplateSection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RuleTemplateSectionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RuleTemplateSection
        //private RuleTemplateSection instance;

        public RuleTemplateSectionTests()
        {
            // TODO uncomment below to create an instance of RuleTemplateSection
            //instance = new RuleTemplateSection();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RuleTemplateSection
        /// </summary>
        [Fact]
        public void RuleTemplateSectionInstanceTest()
        {
            // TODO uncomment below to test "IsType" RuleTemplateSection
            //Assert.IsType<RuleTemplateSection>(instance);
        }

        /// <summary>
        /// Test the property 'ZoneId'
        /// </summary>
        [Fact]
        public void ZoneIdTest()
        {
            // TODO unit test for the property 'ZoneId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'ZoneContent'
        /// </summary>
        [Fact]
        public void ZoneContentTest()
        {
            // TODO unit test for the property 'ZoneContent'
        }

        /// <summary>
        /// Test the property 'ZoneType'
        /// </summary>
        [Fact]
        public void ZoneTypeTest()
        {
            // TODO unit test for the property 'ZoneType'
        }
    }
}
