/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SearchRequestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchRequestDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchRequestDto
        //private SearchRequestDto instance;

        public SearchRequestDtoTests()
        {
            // TODO uncomment below to create an instance of SearchRequestDto
            //instance = new SearchRequestDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchRequestDto
        /// </summary>
        [Fact]
        public void SearchRequestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchRequestDto
            //Assert.IsType<SearchRequestDto>(instance);
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'Area'
        /// </summary>
        [Fact]
        public void AreaTest()
        {
            // TODO unit test for the property 'Area'
        }

        /// <summary>
        /// Test the property 'Collection'
        /// </summary>
        [Fact]
        public void CollectionTest()
        {
            // TODO unit test for the property 'Collection'
        }

        /// <summary>
        /// Test the property 'VisitorId'
        /// </summary>
        [Fact]
        public void VisitorIdTest()
        {
            // TODO unit test for the property 'VisitorId'
        }

        /// <summary>
        /// Test the property 'Refinements'
        /// </summary>
        [Fact]
        public void RefinementsTest()
        {
            // TODO unit test for the property 'Refinements'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'Skip'
        /// </summary>
        [Fact]
        public void SkipTest()
        {
            // TODO unit test for the property 'Skip'
        }

        /// <summary>
        /// Test the property 'BiasingProfile'
        /// </summary>
        [Fact]
        public void BiasingProfileTest()
        {
            // TODO unit test for the property 'BiasingProfile'
        }

        /// <summary>
        /// Test the property 'Biasing'
        /// </summary>
        [Fact]
        public void BiasingTest()
        {
            // TODO unit test for the property 'Biasing'
        }

        /// <summary>
        /// Test the property 'CustomUrlParams'
        /// </summary>
        [Fact]
        public void CustomUrlParamsTest()
        {
            // TODO unit test for the property 'CustomUrlParams'
        }

        /// <summary>
        /// Test the property 'Sorts'
        /// </summary>
        [Fact]
        public void SortsTest()
        {
            // TODO unit test for the property 'Sorts'
        }

        /// <summary>
        /// Test the property 'IncludedNavigations'
        /// </summary>
        [Fact]
        public void IncludedNavigationsTest()
        {
            // TODO unit test for the property 'IncludedNavigations'
        }

        /// <summary>
        /// Test the property 'ExcludedNavigations'
        /// </summary>
        [Fact]
        public void ExcludedNavigationsTest()
        {
            // TODO unit test for the property 'ExcludedNavigations'
        }

        /// <summary>
        /// Test the property 'DynamicFacet'
        /// </summary>
        [Fact]
        public void DynamicFacetTest()
        {
            // TODO unit test for the property 'DynamicFacet'
        }

        /// <summary>
        /// Test the property 'VariantRollupKeys'
        /// </summary>
        [Fact]
        public void VariantRollupKeysTest()
        {
            // TODO unit test for the property 'VariantRollupKeys'
        }

        /// <summary>
        /// Test the property 'PreFilter'
        /// </summary>
        [Fact]
        public void PreFilterTest()
        {
            // TODO unit test for the property 'PreFilter'
        }

        /// <summary>
        /// Test the property 'Site'
        /// </summary>
        [Fact]
        public void SiteTest()
        {
            // TODO unit test for the property 'Site'
        }

        /// <summary>
        /// Test the property 'ResponseMask'
        /// </summary>
        [Fact]
        public void ResponseMaskTest()
        {
            // TODO unit test for the property 'ResponseMask'
        }

        /// <summary>
        /// Test the property 'PageCategories'
        /// </summary>
        [Fact]
        public void PageCategoriesTest()
        {
            // TODO unit test for the property 'PageCategories'
        }

        /// <summary>
        /// Test the property 'SpellCorrectionMode'
        /// </summary>
        [Fact]
        public void SpellCorrectionModeTest()
        {
            // TODO unit test for the property 'SpellCorrectionMode'
        }

        /// <summary>
        /// Test the property 'IncludeExpandedResults'
        /// </summary>
        [Fact]
        public void IncludeExpandedResultsTest()
        {
            // TODO unit test for the property 'IncludeExpandedResults'
        }

        /// <summary>
        /// Test the property 'PinUnexpandedResults'
        /// </summary>
        [Fact]
        public void PinUnexpandedResultsTest()
        {
            // TODO unit test for the property 'PinUnexpandedResults'
        }

        /// <summary>
        /// Test the property 'Debug'
        /// </summary>
        [Fact]
        public void DebugTest()
        {
            // TODO unit test for the property 'Debug'
        }

        /// <summary>
        /// Test the property 'FacetLimit'
        /// </summary>
        [Fact]
        public void FacetLimitTest()
        {
            // TODO unit test for the property 'FacetLimit'
        }

        /// <summary>
        /// Test the property 'LoginId'
        /// </summary>
        [Fact]
        public void LoginIdTest()
        {
            // TODO unit test for the property 'LoginId'
        }

        /// <summary>
        /// Test the property 'Overwrites'
        /// </summary>
        [Fact]
        public void OverwritesTest()
        {
            // TODO unit test for the property 'Overwrites'
        }
    }
}
