/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SearchResults
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchResultsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchResults
        //private SearchResults instance;

        public SearchResultsTests()
        {
            // TODO uncomment below to create an instance of SearchResults
            //instance = new SearchResults();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchResults
        /// </summary>
        [Fact]
        public void SearchResultsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchResults
            //Assert.IsType<SearchResults>(instance);
        }

        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Fact]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }

        /// <summary>
        /// Test the property 'SearchTerms'
        /// </summary>
        [Fact]
        public void SearchTermsTest()
        {
            // TODO unit test for the property 'SearchTerms'
        }

        /// <summary>
        /// Test the property 'ExtendedAttributes'
        /// </summary>
        [Fact]
        public void ExtendedAttributesTest()
        {
            // TODO unit test for the property 'ExtendedAttributes'
        }

        /// <summary>
        /// Test the property 'AttributeResults'
        /// </summary>
        [Fact]
        public void AttributeResultsTest()
        {
            // TODO unit test for the property 'AttributeResults'
        }

        /// <summary>
        /// Test the property 'SiteFilter'
        /// </summary>
        [Fact]
        public void SiteFilterTest()
        {
            // TODO unit test for the property 'SiteFilter'
        }
    }
}
