/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SearchResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchResponseDto
        //private SearchResponseDto instance;

        public SearchResponseDtoTests()
        {
            // TODO uncomment below to create an instance of SearchResponseDto
            //instance = new SearchResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchResponseDto
        /// </summary>
        [Fact]
        public void SearchResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchResponseDto
            //Assert.IsType<SearchResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Area'
        /// </summary>
        [Fact]
        public void AreaTest()
        {
            // TODO unit test for the property 'Area'
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }

        /// <summary>
        /// Test the property 'CorrectedQuery'
        /// </summary>
        [Fact]
        public void CorrectedQueryTest()
        {
            // TODO unit test for the property 'CorrectedQuery'
        }

        /// <summary>
        /// Test the property 'BiasingProfile'
        /// </summary>
        [Fact]
        public void BiasingProfileTest()
        {
            // TODO unit test for the property 'BiasingProfile'
        }

        /// <summary>
        /// Test the property 'BiasingProfileAppliedId'
        /// </summary>
        [Fact]
        public void BiasingProfileAppliedIdTest()
        {
            // TODO unit test for the property 'BiasingProfileAppliedId'
        }

        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }

        /// <summary>
        /// Test the property 'OriginalRequest'
        /// </summary>
        [Fact]
        public void OriginalRequestTest()
        {
            // TODO unit test for the property 'OriginalRequest'
        }

        /// <summary>
        /// Test the property 'Records'
        /// </summary>
        [Fact]
        public void RecordsTest()
        {
            // TODO unit test for the property 'Records'
        }

        /// <summary>
        /// Test the property 'TotalRecordCount'
        /// </summary>
        [Fact]
        public void TotalRecordCountTest()
        {
            // TODO unit test for the property 'TotalRecordCount'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'PageInfo'
        /// </summary>
        [Fact]
        public void PageInfoTest()
        {
            // TODO unit test for the property 'PageInfo'
        }

        /// <summary>
        /// Test the property 'AvailableNavigation'
        /// </summary>
        [Fact]
        public void AvailableNavigationTest()
        {
            // TODO unit test for the property 'AvailableNavigation'
        }

        /// <summary>
        /// Test the property 'SelectedNavigation'
        /// </summary>
        [Fact]
        public void SelectedNavigationTest()
        {
            // TODO unit test for the property 'SelectedNavigation'
        }

        /// <summary>
        /// Test the property 'Redirect'
        /// </summary>
        [Fact]
        public void RedirectTest()
        {
            // TODO unit test for the property 'Redirect'
        }

        /// <summary>
        /// Test the property 'Experiments'
        /// </summary>
        [Fact]
        public void ExperimentsTest()
        {
            // TODO unit test for the property 'Experiments'
        }

        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Fact]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }

        /// <summary>
        /// Test the property 'Empty'
        /// </summary>
        [Fact]
        public void EmptyTest()
        {
            // TODO unit test for the property 'Empty'
        }

        /// <summary>
        /// Test the property 'SiteParams'
        /// </summary>
        [Fact]
        public void SiteParamsTest()
        {
            // TODO unit test for the property 'SiteParams'
        }

        /// <summary>
        /// Test the property 'Debug'
        /// </summary>
        [Fact]
        public void DebugTest()
        {
            // TODO unit test for the property 'Debug'
        }

        /// <summary>
        /// Test the property 'Warnings'
        /// </summary>
        [Fact]
        public void WarningsTest()
        {
            // TODO unit test for the property 'Warnings'
        }

        /// <summary>
        /// Test the property 'IncludeExpandedResults'
        /// </summary>
        [Fact]
        public void IncludeExpandedResultsTest()
        {
            // TODO unit test for the property 'IncludeExpandedResults'
        }

        /// <summary>
        /// Test the property 'FacetLimit'
        /// </summary>
        [Fact]
        public void FacetLimitTest()
        {
            // TODO unit test for the property 'FacetLimit'
        }

        /// <summary>
        /// Test the property 'RedirectMetadata'
        /// </summary>
        [Fact]
        public void RedirectMetadataTest()
        {
            // TODO unit test for the property 'RedirectMetadata'
        }
    }
}
