/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SearchResultsStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchResultsStatsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchResultsStats
        //private SearchResultsStats instance;

        public SearchResultsStatsTests()
        {
            // TODO uncomment below to create an instance of SearchResultsStats
            //instance = new SearchResultsStats();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchResultsStats
        /// </summary>
        [Fact]
        public void SearchResultsStatsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchResultsStats
            //Assert.IsType<SearchResultsStats>(instance);
        }

        /// <summary>
        /// Test the property 'SearchCount'
        /// </summary>
        [Fact]
        public void SearchCountTest()
        {
            // TODO unit test for the property 'SearchCount'
        }

        /// <summary>
        /// Test the property 'AutocompleteResponse'
        /// </summary>
        [Fact]
        public void AutocompleteResponseTest()
        {
            // TODO unit test for the property 'AutocompleteResponse'
        }

        /// <summary>
        /// Test the property 'ExtendedAttributesCount'
        /// </summary>
        [Fact]
        public void ExtendedAttributesCountTest()
        {
            // TODO unit test for the property 'ExtendedAttributesCount'
        }

        /// <summary>
        /// Test the property 'ExtendedAttributesResponse'
        /// </summary>
        [Fact]
        public void ExtendedAttributesResponseTest()
        {
            // TODO unit test for the property 'ExtendedAttributesResponse'
        }
    }
}
