/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SpellCorrectionMode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SpellCorrectionModeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SpellCorrectionMode
        //private SpellCorrectionMode instance;

        public SpellCorrectionModeTests()
        {
            // TODO uncomment below to create an instance of SpellCorrectionMode
            //instance = new SpellCorrectionMode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SpellCorrectionMode
        /// </summary>
        [Fact]
        public void SpellCorrectionModeInstanceTest()
        {
            // TODO uncomment below to test "IsType" SpellCorrectionMode
            //Assert.IsType<SpellCorrectionMode>(instance);
        }
    }
}
