/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TemplateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplateDto
        //private TemplateDto instance;

        public TemplateDtoTests()
        {
            // TODO uncomment below to create an instance of TemplateDto
            //instance = new TemplateDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplateDto
        /// </summary>
        [Fact]
        public void TemplateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplateDto
            //Assert.IsType<TemplateDto>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'RuleName'
        /// </summary>
        [Fact]
        public void RuleNameTest()
        {
            // TODO unit test for the property 'RuleName'
        }

        /// <summary>
        /// Test the property 'TriggerSet'
        /// </summary>
        [Fact]
        public void TriggerSetTest()
        {
            // TODO unit test for the property 'TriggerSet'
        }

        /// <summary>
        /// Test the property 'Zones'
        /// </summary>
        [Fact]
        public void ZonesTest()
        {
            // TODO unit test for the property 'Zones'
        }
    }
}
