/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GroupByInc.RetailApi.Client.Model;
using GroupByInc.RetailApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GroupByInc.RetailApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TriggerSet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TriggerSetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TriggerSet
        //private TriggerSet instance;

        public TriggerSetTests()
        {
            // TODO uncomment below to create an instance of TriggerSet
            //instance = new TriggerSet();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TriggerSet
        /// </summary>
        [Fact]
        public void TriggerSetInstanceTest()
        {
            // TODO uncomment below to test "IsType" TriggerSet
            //Assert.IsType<TriggerSet>(instance);
        }

        /// <summary>
        /// Test the property 'QueryPatternTriggers'
        /// </summary>
        [Fact]
        public void QueryPatternTriggersTest()
        {
            // TODO unit test for the property 'QueryPatternTriggers'
        }

        /// <summary>
        /// Test the property 'SelectedRefinementTriggers'
        /// </summary>
        [Fact]
        public void SelectedRefinementTriggersTest()
        {
            // TODO unit test for the property 'SelectedRefinementTriggers'
        }

        /// <summary>
        /// Test the property 'CustomParameterTriggers'
        /// </summary>
        [Fact]
        public void CustomParameterTriggersTest()
        {
            // TODO unit test for the property 'CustomParameterTriggers'
        }
    }
}
